#!/bin/bash

systemctl stop nginx &>> /var/log/nginx_security.log

cd /etc/systemd/system
[ -d nginx.service.d ] || mkdir nginx.service.d
cd nginx.service.d


cat << . > override.conf
[Service]
User=www-data
Group=www-data
AmbientCapabilities=CAP_NET_BIND_SERVICE
RuntimeDirectory=nginx
PIDFile=/run/nginx/nginx.pid
.

cd /etc/nginx/
sed -i '/pid/ s/|/run/|/run/nginx/' ngninx.conf 

sudo systemctl daemmctl daemon-reload  &>> /var/log/nginx_security.log

cat << . >> override.conf 
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
LockPersonality=true
SystemCallFiler=@system-service
SystemCallErrorNumber=EPERM
.

systemctl daemon-reload  &>> /var/log/nginx_security.log

systemctl restart nginx &>> /var/log/nginx_security.log 

echo "nginx is secure" | systemd-cat -t "service-hardening"


