#!/bin/bash

systemctl stop nginx &>> nginx_security.log

cd /etc/systemd/system
mkdir nginx.service.d
cd nginx.service.d

cat << . > override.conf
[Service]
User=www-data
Group=www-data
AmbientCapabilities=CAP_NET_BIND_SERVICE
RuntimeDirectory=nginx
PIDFile=/run/nginx/nginx.pid
.

cd /etc/nginx/
sed -i '/pid/ s/|/run/|/run/nginx/' ngninx.conf 

sudo systemctl daemmctl daemon-reload  &>> nginx_security.log

cat << . >> override.conf 
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
LockPersonality=true
SystemCallFiler=@system-service
SystemCallErrorNumber=EPERM
.

systemctl daemon-reload  &>> nginx_security.log

systemctl restart nginx  &| systemd-cat 

echo "nginx is secure" >> nginx_security.log


