- name: Install packages
  package:
    name: "{{ webserver_packages }}"
    state: latest

- name: Harden service
  copy:
    dest: /etc/systemd/system
    src: etc/systemd/system/nginx.service.d
    owner: root
    group: root  
    mode: 0644
  notify: 
    - Reload DAEMON

- name: Add base NGINX configuration file
  copy:
    dest: /etc/nginx/nginx.conf
    src: etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: 
    - Reload NGINX
